[tool.poetry]
name = "icpc_problem_renderer"
version = "0.0.1"
description = ""
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.1.0"

[tool.poetry.group.production.dependencies]
gunicorn = "^23.0.0"
